Rails:
  Enabled: true
Documentation:
  Enabled: false
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'bin/*'
    - 'Gemfile'
    - 'spec/**/*'
Style/SymbolArray:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/LineLength:
  Max: 130
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 120